"""
Seed data for Sri Ma Vidyalaya CBSE School:
- Class sections for grades VI–X
- Subject masters (unique catalog)
- Per-section subject period allotments (775 rows from constraints PDF)
- ~40 actual scheduling constraint rules (activity-days, subject rules, teacher rules)
"""

# Unique subjects with code & default color
SUBJECTS = [
    ("English O/A", "ENGOA", "#0055FF", False),
    ("English I/A", "ENGIA", "#0055FF", False),
    ("English Reg", "ENGRG", "#0055FF", False),
    ("English", "ENG", "#0055FF", False),
    ("Hindi/Sanskrit", "HINSKT", "#FF3B30", False),
    ("Hindi/Marathi/Sanskrit", "HMS", "#FF3B30", False),
    ("Marathi", "MAR", "#FFCC00", False),
    ("Basic Marathi", "BMAR", "#FFCC00", False),
    ("General Science", "GSC", "#10B981", False),
    ("Mathematics", "MAT", "#002FA7", False),
    ("Math Lab", "MLAB", "#002FA7", True),
    ("Social Studies", "SS", "#8B5CF6", False),
    ("Algebra", "ALG", "#002FA7", False),
    ("Geometry", "GEOM", "#002FA7", False),
    ("Physics", "PHY", "#10B981", False),
    ("Chemistry", "CHEM", "#10B981", True),
    ("Biology", "BIO", "#10B981", False),
    ("History", "HIST", "#8B5CF6", False),
    ("Geography", "GEOG", "#8B5CF6", False),
    ("Computer", "COMP", "#06B6D4", True),
    ("Yoga", "YOGA", "#84CC16", False),
    ("Physical Education", "PE", "#F97316", False),
    ("Art / Library", "ARTLIB", "#EC4899", False),
    ("Music", "MUS", "#A855F7", False),
    ("Mass Drill", "MD", "#F97316", False),
    ("General Knowledge", "GK", "#71717A", False),
    ("Robotics", "ROBO", "#06B6D4", True),
    ("Value Education", "VE", "#FFCC00", False),
    ("Test", "TEST", "#71717A", False),
    ("Activity", "ACT", "#FFCC00", False),
    ("Science Activity", "SCIACT", "#10B981", False),
    ("Scout / Guide", "SCTGUI", "#84CC16", False),
    ("Art", "ART", "#EC4899", False),
]

# Sections per grade (from the PDF rows)
GRADE_SECTIONS = {
    "VI":  ["A", "B", "C", "D", "E", "F", "G", "H", "J"],
    "VII": ["A", "B", "C", "D", "E", "F", "G", "H", "J", "K"],
    "VIII":["A", "B", "C", "D", "E", "F", "G", "H", "J"],
    "IX":  ["A", "B", "C", "D", "E", "F", "G", "H"],
    "X":   ["A", "B", "C", "D", "E", "F", "G"],
}

# Period allotment: dict keyed by grade => list of (subject_code, sections_with_periods)
# Where sections_with_periods is a dict {section: periods_per_week}
# Built from constraint PDF rows 10-745.
def _e(default, **overrides):
    """Helper: build per-section dict with a default value and overrides."""
    base = {}
    for sec in "ABCDEFGHJK":
        base[sec] = default
    base.update(overrides)
    return base

ALLOTMENTS = {
    "VI": [
        # English split A/B = O/A, C/D = I/A, E-J = Reg
        ("ENGOA", {"A": 6, "B": 6}),
        ("ENGIA", {"C": 6, "D": 6}),
        ("ENGRG", {"E": 7, "F": 7, "G": 7, "H": 7, "J": 7}),
        ("HINSKT", {"A": 6, "B": 6, "C": 6, "D": 6, "E": 7, "F": 7, "G": 7, "H": 7, "J": 7}),
        ("MAR",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4, "J": 4}),
        ("GSC",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6, "J": 6}),
        ("MAT",   {"A": 7, "B": 7, "C": 7, "D": 7, "E": 7, "F": 7, "G": 7, "H": 7, "J": 7}),
        ("MLAB",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("SS",    {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6, "J": 6}),
        ("COMP",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("YOGA",  {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("PE",    {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("ARTLIB",{"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("MUS",   {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("MD",    {"B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("ROBO",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("VE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("ACT",   {"A": 6, "B": 6, "C": 4, "D": 4, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
    ],
    "VII": [
        ("ENGOA", {"A": 7, "B": 7}),
        ("ENGIA", {"C": 7, "D": 7}),
        ("ENGRG", {"E": 8, "F": 8, "G": 8, "H": 8, "J": 8, "K": 8}),
        ("HINSKT",{"A": 6, "B": 6, "C": 6, "D": 6, "E": 7, "F": 7, "G": 7, "H": 7, "J": 7, "K": 7}),
        ("MAR",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4, "J": 4, "K": 4}),
        ("GSC",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6, "J": 6, "K": 6}),
        ("MAT",   {"A": 7, "B": 7, "C": 7, "D": 7, "E": 7, "F": 7, "G": 7, "H": 7, "J": 7, "K": 7}),
        ("MLAB",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("SS",    {"A": 5, "B": 5, "C": 5, "D": 5, "E": 5, "F": 5, "G": 5, "H": 5, "J": 5, "K": 5}),
        ("COMP",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2, "K": 2}),
        ("YOGA",  {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("PE",    {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("ARTLIB",{"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2, "K": 2}),
        ("MUS",   {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("TEST",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("ROBO",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2, "K": 2}),
        ("VE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1, "K": 1}),
        ("ACT",   {"A": 6, "B": 6, "C": 4, "D": 4, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2, "K": 2}),
    ],
    "VIII": [
        ("ENGOA", {"A": 6, "B": 6}),
        ("ENGIA", {"C": 6, "D": 6}),
        ("ENGRG", {"E": 7, "F": 7, "G": 7, "H": 7, "J": 7}),
        ("HINSKT",{"A": 6, "B": 6, "C": 6, "D": 6, "E": 7, "F": 7, "G": 7, "H": 7, "J": 7}),
        ("MAR",   {"A": 5, "B": 5, "C": 5, "D": 5, "E": 5, "F": 5, "G": 5, "H": 5, "J": 5}),
        ("GSC",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6, "J": 6}),
        ("MAT",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6, "J": 6}),
        ("MLAB",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("SS",    {"A": 5, "B": 5, "C": 5, "D": 5, "E": 5, "F": 5, "G": 5, "H": 5, "J": 5}),
        ("COMP",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("YOGA",  {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("PE",    {"C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("ARTLIB",{"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("MUS",   {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("SCTGUI",{"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("ROBO",  {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
        ("VE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1, "J": 1}),
        ("ACT",   {"A": 6, "B": 6, "C": 4, "D": 4, "E": 2, "F": 2, "G": 2, "H": 2, "J": 2}),
    ],
    "IX": [
        ("ENG",   {"A": 7, "B": 7, "C": 7, "D": 7, "E": 7, "F": 7, "G": 7, "H": 7}),
        ("HMS",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6, "H": 6}),
        ("BMAR",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1}),
        ("ALG",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4}),
        ("GEOM",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4}),
        ("PHY",   {"A": 3, "B": 3, "C": 3, "D": 3, "E": 3, "F": 3, "G": 3, "H": 3}),
        ("CHEM",  {"A": 3, "B": 3, "C": 3, "D": 3, "E": 3, "F": 3, "G": 3, "H": 3}),
        ("BIO",   {"A": 3, "B": 3, "C": 3, "D": 3, "E": 3, "F": 3, "G": 3, "H": 3}),
        ("HIST",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4}),
        ("GEOG",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4}),
        ("COMP",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4, "H": 4}),
        ("ART",   {"A": 2, "B": 2, "C": 2, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1}),
        ("PE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1}),
        ("YOGA",  {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1}),
        ("SCTGUI",{"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2}),
        ("ACT",   {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2, "H": 2}),
        ("VE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1, "H": 1}),
    ],
    "X": [
        ("ENG",   {"A": 7, "B": 7, "C": 7, "D": 7, "E": 7, "F": 7, "G": 7}),
        ("HMS",   {"A": 6, "B": 6, "C": 6, "D": 6, "E": 6, "F": 6, "G": 6}),
        ("ALG",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("GEOM",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("PHY",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("CHEM",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("BIO",   {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("HIST",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("GEOG",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("COMP",  {"A": 4, "B": 4, "C": 4, "D": 4, "E": 4, "F": 4, "G": 4}),
        ("ART",   {"A": 1, "B": 1, "C": 1, "D": 2, "E": 2, "F": 2, "G": 1}),
        ("BMAR",  {"D": 1, "E": 1, "F": 1, "G": 1}),
        ("PE",    {"A": 1, "B": 1, "C": 1, "D": 1, "E": 1, "F": 1, "G": 1}),
        ("ACT",   {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 2, "G": 2}),
    ],
}

# The ~40 actual scheduling rules from the PDF
RULES = [
    # ----- Activity Day Schedules -----
    {"name": "Class 6 — Outdoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 6 outdoor activities on Tue, Wed, Thu",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 6"}, {"field": "day", "op": "∈", "value": "Tue,Wed,Thu"}],
     "action": {"type": "prefer", "value": "outdoor"}},
    {"name": "Class 6 — Regular Day", "category": "sequence", "severity": "soft",
     "description": "Class 6 regular day on Wed",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 6"}, {"field": "day", "op": "=", "value": "Wed"}],
     "action": {"type": "prefer", "value": "regular"}},
    {"name": "Class 6 — Indoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 6 indoor activities on Wed, Thu",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 6"}, {"field": "day", "op": "∈", "value": "Wed,Thu"}],
     "action": {"type": "prefer", "value": "indoor"}},
    {"name": "Class 7 — Outdoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 7 outdoor activities on Mon, Tue, Wed",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 7"}, {"field": "day", "op": "∈", "value": "Mon,Tue,Wed"}],
     "action": {"type": "prefer", "value": "outdoor"}},
    {"name": "Class 7 — Regular Day", "category": "sequence", "severity": "soft",
     "description": "Class 7 regular day on Mon",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 7"}, {"field": "day", "op": "=", "value": "Mon"}],
     "action": {"type": "prefer", "value": "regular"}},
    {"name": "Class 7 — Indoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 7 indoor activities on Mon, Thu",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 7"}, {"field": "day", "op": "∈", "value": "Mon,Thu"}],
     "action": {"type": "prefer", "value": "indoor"}},
    {"name": "Class 8 — Outdoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 8 outdoor activities on Mon, Tue, Thu",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 8"}, {"field": "day", "op": "∈", "value": "Mon,Tue,Thu"}],
     "action": {"type": "prefer", "value": "outdoor"}},
    {"name": "Class 8 — Regular Day", "category": "sequence", "severity": "soft",
     "description": "Class 8 regular day on Tue",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 8"}, {"field": "day", "op": "=", "value": "Tue"}],
     "action": {"type": "prefer", "value": "regular"}},
    {"name": "Class 8 — Indoor Days", "category": "sequence", "severity": "soft",
     "description": "Class 8 indoor activities on Tue, Thu",
     "conditions": [{"field": "class", "op": "=", "value": "Standard 8"}, {"field": "day", "op": "∈", "value": "Tue,Thu"}],
     "action": {"type": "prefer", "value": "indoor"}},

    # ----- Subject scheduling rules -----
    {"name": "Activity in first two periods", "category": "sequence", "severity": "hard",
     "description": "Activity – 1st two periods according to their schedule",
     "conditions": [{"field": "subject", "op": "=", "value": "Activity"}],
     "action": {"type": "require", "value": "period ∈ P1,P2"}},
    {"name": "Yoga — Mon-Fri allowed periods", "category": "preference", "severity": "hard",
     "description": "Yoga - Mon to Fri – periods 1–5 and 7, 8",
     "conditions": [{"field": "subject", "op": "=", "value": "Yoga"}, {"field": "day", "op": "∈", "value": "Mon,Tue,Wed,Thu,Fri"}],
     "action": {"type": "require", "value": "period ∈ P1,P2,P3,P4,P5,P7,P8"}},
    {"name": "Yoga — Saturday allowed periods", "category": "preference", "severity": "hard",
     "description": "Saturday – periods 1–4 and 6",
     "conditions": [{"field": "subject", "op": "=", "value": "Yoga"}, {"field": "day", "op": "=", "value": "Sat"}],
     "action": {"type": "require", "value": "period ∈ P1,P2,P3,P4,P6"}},
    {"name": "Yoga — no simultaneous classes", "category": "clash", "severity": "hard",
     "description": "No two classes can be given Yoga simultaneously",
     "conditions": [{"field": "subject", "op": "=", "value": "Yoga"}],
     "action": {"type": "forbid", "value": "simultaneous_classes"}},
    {"name": "Math Lab — 1 period for Class 6, 7, 8", "category": "workload", "severity": "hard",
     "description": "Class 6, 7, 8 have 1 period for Math Lab",
     "conditions": [{"field": "subject", "op": "=", "value": "Math Lab"}, {"field": "class", "op": "∈", "value": "Standard 6,Standard 7,Standard 8"}],
     "action": {"type": "limit", "value": "1 per week"}},
    {"name": "Math Lab — no simultaneous classes", "category": "clash", "severity": "hard",
     "description": "No 2 classes can have Math Lab simultaneously",
     "conditions": [{"field": "subject", "op": "=", "value": "Math Lab"}],
     "action": {"type": "forbid", "value": "simultaneous_classes"}},
    {"name": "Computer Class 6-8 — consecutive practical", "category": "sequence", "severity": "hard",
     "description": "Computer – Class 6, 7, 8 have 2 periods. One theory and 1 practical to be given consecutively.",
     "conditions": [{"field": "subject", "op": "=", "value": "Computer"}, {"field": "class", "op": "∈", "value": "Standard 6,Standard 7,Standard 8"}],
     "action": {"type": "require", "value": "consecutive"}},
    {"name": "Computer Class 9-10 — consecutive pair", "category": "sequence", "severity": "hard",
     "description": "Class 9, 10 have 4 periods. 1 theory + 1 practical consecutive.",
     "conditions": [{"field": "subject", "op": "=", "value": "Computer"}, {"field": "class", "op": "∈", "value": "Standard 9,Standard 10"}],
     "action": {"type": "require", "value": "1 consecutive pair"}},
    {"name": "Computer Class 9-10 — separate-day pair", "category": "sequence", "severity": "soft",
     "description": "Other 1 theory + 1 practical can be on separate days",
     "conditions": [{"field": "subject", "op": "=", "value": "Computer"}, {"field": "class", "op": "∈", "value": "Standard 9,Standard 10"}],
     "action": {"type": "prefer", "value": "separate days"}},
    {"name": "Computer Class 10 — Saturday practical", "category": "preference", "severity": "soft",
     "description": "Class 10 single practical on Saturday",
     "conditions": [{"field": "subject", "op": "=", "value": "Computer"}, {"field": "class", "op": "=", "value": "Standard 10"}, {"field": "day", "op": "=", "value": "Sat"}],
     "action": {"type": "prefer", "value": "practical"}},
    {"name": "Computer Lab availability check", "category": "room", "severity": "hard",
     "description": "When allotting practical, availability of Lab must be checked",
     "conditions": [{"field": "subject", "op": "=", "value": "Computer"}],
     "action": {"type": "require", "value": "lab_free"}},
    {"name": "Art / Library — continuous only", "category": "sequence", "severity": "hard",
     "description": "Art/Lib to be given in continuous periods only",
     "conditions": [{"field": "subject", "op": "=", "value": "Art / Library"}],
     "action": {"type": "require", "value": "consecutive"}},
    {"name": "Value Education — clubbing", "category": "preference", "severity": "hard",
     "description": "All divisions of same standard are clubbed for V.E.",
     "conditions": [{"field": "subject", "op": "=", "value": "Value Education"}],
     "action": {"type": "require", "value": "clubbed_by_grade"}},
    {"name": "V.E. — 5th period reserved", "category": "preference", "severity": "hard",
     "description": "Every day 5th period reserved for V.E. for one class",
     "conditions": [{"field": "subject", "op": "=", "value": "Value Education"}],
     "action": {"type": "require", "value": "period = P5"}},
    {"name": "Scout/Guide Class 8 — Fri P7-P8", "category": "preference", "severity": "hard",
     "description": "Class 8 SC/Guide on Friday 7th-8th period",
     "conditions": [{"field": "subject", "op": "=", "value": "Scout / Guide"}, {"field": "class", "op": "=", "value": "Standard 8"}],
     "action": {"type": "require", "value": "Fri P7,P8"}},
    {"name": "Scout/Guide Class 9 — Wed P7-P8", "category": "preference", "severity": "hard",
     "description": "Class 9 SC/Guide on Wed 7th-8th period",
     "conditions": [{"field": "subject", "op": "=", "value": "Scout / Guide"}, {"field": "class", "op": "=", "value": "Standard 9"}],
     "action": {"type": "require", "value": "Wed P7,P8"}},
    {"name": "Robotics Class 6-7 — consecutive", "category": "sequence", "severity": "hard",
     "description": "Class 6, 7 — 2 periods to be given consecutively",
     "conditions": [{"field": "subject", "op": "=", "value": "Robotics"}, {"field": "class", "op": "∈", "value": "Standard 6,Standard 7"}],
     "action": {"type": "require", "value": "consecutive"}},
    {"name": "Saturday — non-allotment subjects", "category": "preference", "severity": "hard",
     "description": "Music, Art/Lib, Computer (Class 6 to 9) cannot be allotted on Saturday",
     "conditions": [{"field": "day", "op": "=", "value": "Sat"}, {"field": "subject", "op": "∈", "value": "Music,Art / Library,Computer"}],
     "action": {"type": "forbid", "value": "for Grade 6-9"}},

    # ----- Teacher constraints -----
    {"name": "Teacher daily period range", "category": "workload", "severity": "hard",
     "description": "Every subject teacher: 6–7 periods per day, minimum 5 on any single day",
     "conditions": [{"field": "teacher", "op": "≠", "value": ""}],
     "action": {"type": "limit", "value": "5 ≤ daily_periods ≤ 7"}},
    {"name": "Teacher break after 3 continuous", "category": "workload", "severity": "hard",
     "description": "Teacher should get a break after every 3 continuous periods",
     "conditions": [{"field": "teacher", "op": "≠", "value": ""}],
     "action": {"type": "require", "value": "break_after_3"}},
    {"name": "Teacher max 2 periods in same class/day", "category": "workload", "severity": "hard",
     "description": "Teacher should not be in the same class for more than 2 periods in a day",
     "conditions": [{"field": "teacher", "op": "≠", "value": ""}],
     "action": {"type": "limit", "value": "max_2_per_class_per_day"}},
    {"name": "GW, ST, AD, AJ — no first 2 periods", "category": "preference", "severity": "hard",
     "description": "GW (Gaikwad), ST (Shivaji), AD (Akshara), AJ (Ashwini Joshi) cannot be allotted first 2 periods",
     "conditions": [{"field": "teacher", "op": "∈", "value": "GW,ST,AD,AJ"}],
     "action": {"type": "forbid", "value": "period ∈ P1,P2"}},
    {"name": "Mini Madam — periods 5–7 only", "category": "preference", "severity": "hard",
     "description": "MN (Mini Nair) can be allotted periods 5th to 7th only",
     "conditions": [{"field": "teacher", "op": "=", "value": "MN"}],
     "action": {"type": "require", "value": "period ∈ P5,P6,P7"}},
    {"name": "HK, MW — no P1, P2, P9", "category": "preference", "severity": "hard",
     "description": "HK (Harpreet) and MW (Meghana) cannot be in 1st, 2nd or 9th periods",
     "conditions": [{"field": "teacher", "op": "∈", "value": "HK,MW"}],
     "action": {"type": "forbid", "value": "period ∈ P1,P2,P9"}},
    {"name": "HK, MN, MW — one free at all times", "category": "preference", "severity": "hard",
     "description": "Among HK, MN, MW — one of the three should always be free",
     "conditions": [{"field": "teacher", "op": "∈", "value": "HK,MN,MW"}],
     "action": {"type": "require", "value": "one_free_per_slot"}},
    {"name": "LI — P6–P9 except Wednesday", "category": "preference", "severity": "hard",
     "description": "LI (Lata Iyer) can be given 6th–9th periods but not on Wednesday",
     "conditions": [{"field": "teacher", "op": "=", "value": "LI"}],
     "action": {"type": "require", "value": "period ∈ P6,P7,P8,P9 AND day ≠ Wed"}},
    {"name": "NP — not P7–P9 weekdays, not Sat P5-P6", "category": "preference", "severity": "hard",
     "description": "NP (Nandini Parsai) cannot have P7–P9 weekdays and Sat P5–P6",
     "conditions": [{"field": "teacher", "op": "=", "value": "NP"}],
     "action": {"type": "forbid", "value": "P7-P9 weekdays, Sat P5-P6"}},
    {"name": "RA — only P8 and P9", "category": "preference", "severity": "hard",
     "description": "RA (Rama Madam) should be allotted only 8th and 9th period",
     "conditions": [{"field": "teacher", "op": "=", "value": "RA"}],
     "action": {"type": "require", "value": "period ∈ P8,P9"}},
    {"name": "SD, GP, SG — no first 3 periods", "category": "preference", "severity": "hard",
     "description": "SD (Seema D), GP (Pushpa), SG (Sagarika) cannot be in first 3 periods Mon–Sat",
     "conditions": [{"field": "teacher", "op": "∈", "value": "SD,GP,SG"}],
     "action": {"type": "forbid", "value": "period ∈ P1,P2,P3"}},
    {"name": "Grade 9-10 teachers — keep 11-12 TT in view", "category": "general", "severity": "soft",
     "description": "Teachers teaching 9th & 10th should be allotted periods keeping their 11th–12th time table in view",
     "conditions": [{"field": "class", "op": "∈", "value": "Standard 9,Standard 10"}],
     "action": {"type": "prefer", "value": "respect_11_12_schedule"}},
]


# Default sections that get created per school
DEFAULT_SECTIONS = [
    {"name": "Kindergarten", "order": 0, "description": "Pre-Primary / Nursery"},
    {"name": "Primary", "order": 1, "description": "Standards 1 to 5"},
    {"name": "Secondary", "order": 2, "description": "Standards 6 to 10"},
    {"name": "Sr.Secondary", "order": 3, "description": "Standards 11 and 12"},
]


# Map grade roman → default section name
GRADE_TO_SECTION = {
    "VI": "Secondary", "VII": "Secondary", "VIII": "Secondary",
    "IX": "Secondary", "X": "Secondary",
}
